# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Daniel Bachler
email: daniel@danielbachler.de
description: > # this means to ignore newlines until "baseurl:"
  The personal website of Daniel Bachler - Software Engineer and Photographer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://danielbachler.de" # the base hostname & protocol for your site
twitter_username: danyx23
github_username:  danyx23
paginate: 5
exclude: ['vendor', 'Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md', 'old-content', 'justfile', '_config.yml']

# Build settings
markdown: kramdown
kramdown:
  input: GFM

plugins: [jekyll-paginate, jekyll-gist, jekyll-feed, jekyll-toc] # add jekyll-feed again!
